### ISSUE TITLE
adding workflow_id to subject seems to be required

### ISSUE THREAD

**Issue by superchris** [8thlight/ex_state#2]
Trying out ex_state_ecto after reading your article. I added a workflow to an existing model. When I went to query it for the first time in iex, i got an error about workflow_id not being a column on the table. I added a migration to add this column to the subject table and it seems to be fixed. I didn't see this documented anywhere. The only odd thing I have done is I added my own migration to create the workflow and workflow_steps table with a regular ole integer primary key instead of UUID so I wouldn't have to mess with the postgres extension. Not sure how this would have affected thing in this way.

**Comment by superchris** [comment]
as a point of comparison, I got rid of my custom migration shenanigans and ran yours as suggested in the docs, but still hit the same issue with not finding a workflow_id on my subject's table

**Comment by kevbuchanan** [comment]
Yes, `workflow_id` is required on the subject table. This is missing from the docs. I will add a section about that piece. Thanks for pointing this out.
